### ISSUE TITLE
Sublime Text 3 shortcuts and snippets

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/meta#11]
Figure out how to easily make your own snippets that don't use keys but rather text shortcuts. Currently, I'm running into issues with too many shortcuts, and I want to be able to do more. Snippets that need to be added:

``` js
module.exports. = exports. = function  () {

}
```

**Comment by eyalev** [comment]
My current approach to too-many-shortcuts:

[I'm on Ubuntu] I have my regular terminal app (Gnome-terminal) and a "Launcher" terminal app (terminator). When I hit a keyboard shortcut (Alt-I) the launcher-terminal is brought into focus and initiated with [`fzf`](https://github.com/junegunn/fzf) prompt. 

Then I can search my command history which is "tagged" by various words in an ENV variable before the command itself.

E.g: 
`$ c='some tags and associations from my mind' the-actual-command`

This setup gives me a quick search for various commands; or even just snippets of text I write to terminal (just inside an ENV var without a command).

---

All of this might not be directly related to this issue, but I felt like sharing :)
