### ISSUE TITLE
PR Github to parse commits to close issues in PPs

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/meta#3]
For instance, the commit:

> Fixes the issue in #72

ought to be parsed. An easy way to do this is to use a parser to check the object 
of the commit sentence, and to see if there is a clause between fixes and the 
issue number.

**Comment by RichardLitt** [comment]
Tweeted @github here: https://twitter.com/richlitt/status/566004116950757378

**Comment by jedireza** [comment]
Have you checked this out?
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by RichardLitt** [comment]
Yeah, but where is the code for that? I want to do a PR to see if I can add semantic understanding to it...

**Comment by RichardLitt** [comment]
All GitHub issues will now be tracked on isaacs/github. This is closed as of https://github.com/isaacs/github/issues/357
